Restructured whole project.
most movetile bugs are fixed. lots of features still not implemented

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -9,6 +9,7 @@ COPY package*.json ./
 
 # Install project dependencies
 RUN npm install
+RUN npm list react-dnd react-dnd-html5-backend || echo "Dependencies not found"
 
 # Copy the rest of the application code into the container
 COPY . .
